config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'

  map.resources :users

  map.resource :session

  

  
  map.resources :people
  map.resources :posts
  map.resources :jobs
  map.resources :downloads
  map.resources :application_fields
  map.resources :super_groups
  
  map.namespace :admin do |admin|
    admin.resources :people, :collection => { :move_higher => :post, :move_lower => :post }
    admin.resources :posts
    admin.resources :jobs
    admin.resources :product_groups
    admin.resources :products
    admin.resources :downloads
    admin.resources :application_fields, :collection => { :move_higher => :post, :move_lower => :post }
    admin.resources :application_field_products
    admin.resources :color_names
    admin.resources :super_groups
  end

  
  map.resource :contact_form
  
  map.root :controller => "about", :action => 'index'

  map.imprint 'imprint', :controller => "about", :action => "imprint"
  map.contact_us 'contact_us', :controller => "about", :action => "contact"
  map.sustainability 'sustainability', :controller => "about", :action => "sustainability"
  map.company 'company', :controller => 'about', :action => 'company'
  map.history 'history', :controller => 'about', :action => 'history'
  map.sitemap 'sitemap', :controller => 'about', :action => 'sitemap'
  
  
  map.packaging 'packaging', :controller => 'service', :action => 'packaging'
  map.technical_support 'technical_support', :controller => 'service', :action => 'technical_support'
  map.dosing_systems 'dosing_systems', :controller => 'service', :action => 'dosing_systems'
  map.press 'press', :controller => 'service', :action => 'press'
  map.partner 'partner', :controller => 'service', :action => 'partner'
  map.carbon_black 'carbon_black', :controller => 'product_range', :action => "carbon_black"
  map.toll_manufacturing 'toll_manufacturing', :controller => 'product_range', :action => "toll_manufacturing"
  map.roofolan 'roofolan', :controller => 'product_range', :action => 'roofolan'
  map.admin '/admin', :controller => "posts", :action => "index", :namespace => "admin"
  
  
  map.login  '/login',  :controller => 'session', :action => 'new'
  map.logout '/logout', :controller => 'session', :action => 'destroy'
  
  map.connect '/carbon-black', :controller => 'super_groups', :action => 'show', :id => "carbon-black"
  map.connect '/chromoxid', :controller => 'super_groups', :action => 'show', :id => "chromoxid"
  map.connect '/eisenoxid', :controller => 'super_groups', :action => 'show', :id => "eisenoxid"
  map.connect '/euronox', :controller => 'super_groups', :action => 'show', :id => "euronox"
  map.connect '/euronyl', :controller => 'super_groups', :action => 'show', :id => "euronyl"
  map.connect '/flussigfarben', :controller => 'super_groups', :action => 'show', :id => "flussigfarben"
  map.connect '/fluessigfarben', :controller => 'super_groups', :action => 'show', :id => "flussigfarben"
  map.connect '/slurry', :controller => 'super_groups', :action => 'show', :id => "flussigfarben"
  map.connect '/kasselerbraun', :controller => 'super_groups', :action => 'show', :id => "nussbeize"
  map.connect '/nussbeize', :controller => 'super_groups', :action => 'show', :id => "nussbeize"
  map.connect '/lohnfertigung', :controller => 'super_groups', :action => 'show', :id => "lohnfertigung"
  map.connect '/mischphasenpigmente', :controller => 'super_groups', :action => 'show', :id => "mischphasenpigmente"
  map.connect '/organische-pigmente', :controller => 'super_groups', :action => 'show', :id => "organische-pigmente"
  map.connect '/roofolan', :controller => 'super_groups', :action => 'show', :id => "roofolanr"
  map.connect '/titandioxid', :controller => 'super_groups', :action => 'show', :id => "titandioxid"
  map.connect '/ultramarinblau', :controller => 'super_groups', :action => 'show', :id => "ultramarinblau"
  map.connect '/wismuthvanadat', :controller => 'super_groups', :action => 'show', :id => "wismuthvanadat"
  
  
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
  
end

ActionController::Routing::Translator.translate_from_file 'config/locales', 'i18n-routes.yml'

app/models/product.rb
# -*- encoding : utf-8 -*-
class Product < ActiveRecord::Base
  belongs_to :product_group
  belongs_to :color_name
  has_many :application_field_products
  has_many :application_fields, :through => :application_field_products
  
  validates_presence_of :number
  
  #named_scope :color_name, lambda{ |color_name_id| { :conditions => ['color_name = ?', color_name]} }
  named_scope :valid, :conditions => ["color_name_id IS NOT ? OR color_name_id != ?", nil, 0]
  
end

app/controllers/admin/products_controller.rb
# -*- encoding : utf-8 -*-
class Admin::ProductsController < AdminController
  
  def index
    @search = Product.search(params[:search])
    @products = @search.paginate :per_page => 50, :page => params[:page]
    
    respond_to do |wants|
      wants.html {  }
      wants.csv { }
    end
  end
  
  def new
    @product = Product.new
    
    respond_to do |wants|
      wants.html {  }
    end
  end
  
  def create
    @product = Product.new(params[:product])
    
    respond_to do |wants|
      if @product.save
        flash[:notice] = "Das Produkt wurde erfolgreich erstellt."
        wants.html { redirect_to edit_admin_product_path(@product) }
      else
        flash[:notice] = "Das Produkt konnte nicht gespeichert werden."
        wants.html { render :new }
      end
    end
  end
  
  def edit
    @product = Product.find(params[:id])
    
    respond_to do |wants|
      wants.html { }
    end
  end
  
  def update
    @product = Product.find(params[:id])
    
    respond_to do |wants|
      if @product.update_attributes(params[:product])
        flash[:notice] = "Das Produkt wurde erfolgreich aktualisiert."
        wants.html { redirect_to edit_admin_product_path(@product) }
      end
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    
    respond_to do |wants|
      wants.html { redirect_to admin_products_path}
    end
  end
  
end

app/helpers/product_helper.rb
# -*- encoding : utf-8 -*-
module ProductHelper
  
  def color_cell(product,shade,application_field, color_name, product_group)
    style = "text-align:center;"
    style += "background-color:##{shade}; border: 1px solid #ccc;" if shade.present?
    style += "background-image: url('../images/#{application_field.permalink}_overlay.png')" if application_field.id == 2101 && shade.present? # Wood Plastic Composites
    content_tag :td, :width => "140", :style => style do
      inner = ""
      if shade.present?
        if product.url.present?
          inner += link_to image_tag("blank.gif", :width => "100%", :height => "50", :border => "0", :alt => APP_CONFIG[:keywords]), "#{product.url}?tx_editfiltersystem_pi1[name]=#{product.number}", :target => "_blank", :title => "#{product.number} (#{localized_attr_for(product_group, :title)}, #{localized_attr_for(color_name,:title)})"
        else
          inner += image_tag("blank2.gif", :width => "100%", :height => "50", :border => "0", :alt => APP_CONFIG[:keywords])
          inner
        end
      else
        I18n.t(:not_recommended) if application_field.id == 700
      end
    end
  end
end

app/views/admin/products/_form.html.haml
%p#color_number
  = f.label :number, "Farbnummer"
  %br
  = f.text_field :number
  %span.color_number_notice z.B. 180 B
  
  
%p
  = f.label :color_name_id, "Farbname"
  = f.select :color_name_id, ColorName.all.map {|c| [c.title_de, c.id]}, :include_blank => true

#choose_color
  %p#shade_1.color_shade
    = f.label :shade_1, "Ton 1"
    %br
    = f.text_field :shade_1, :class => "colorfield"
    %span.color_preview{:style => "background-color:##{f.object.shade_1}"}
    %span.shade_notice Bitte Farbton für die <br />linke Spalte auswählen

  %p#shade_2.color_shade
    = f.label :shade_2, "Ton 2"
    %br
    = f.text_field :shade_2, :class => "colorfield"
    %span.color_preview{:style => "background-color:##{f.object.shade_2}"}
    %span.shade_notice Bitte Farbton für die <br />rechte Spalte auswählen

%p
  = f.label :product_group_id, "Produktgruppe"
  = f.select :product_group_id, ProductGroup.all.map {|c| [c.title_de, c.id]}

%p{ :style => "position: relative", :class => "labeled_field"}
  = f.label :url, "URL"
  = f.text_field :url
  %span.placeholder= "http://www.example.com"

%hr
%h1= "Anwendungsgebiete (A-Z)"
%ul.application_fields
  - ApplicationField.ordered_name.each do |application_field|
    - unless application_field.children.present?
      %li
        = check_box_tag 'product[application_field_ids][]', application_field.id, f.object.application_fields.include?(application_field)
        %label= application_field.title_de
%hr
%h1= "Zusatzinfo"

%table{ :cellspacing => "0", :cellpadding => "0", :border => "0", :class => "text_area", :width => "600"}
  %tr
    %td{:width => "290"}
      %h2.de= "Deutsch"
  
      %p
        = f.label :info_de, "Info (DE)"
        %br
        = f.text_area :info_de
    %td.spacer{ :width => "20"}
    %td{:width => "290"}
      %h2.en= "Englisch"
      %p
        = f.label :info_en, "Info (EN)"
        %br
        = f.text_area :info_en
%p.note
  = "Einfache Textformatierungen:"
  %br
  = "*fett*, \"link\":http://www.link.de, mehr Beispiele hier: #{link_to 'textile', 'http://www.textism.com/tools/textile/', :class => 'view_website'}"

app/views/admin/products/_product.html.haml
- content_tag :tr, product, :class => "list_item #{cycle('odd','even')}" do
  %td
    %b= "#{product.number} (#{product.color_name.title_de}/#{product.color_name.title_en})" if product.color_name.present?
    - unless localized_attr_for(product, :info).blank?
      %p.small
        = "<b>Info</b>: #{localized_attr_for(product, :info)}"
  %td{ :width => "115", :style => "background-color:##{product.shade_1}; border: 1px solid #CCC"}
    - if product.url.present?
      = link_to image_tag("blank.gif", :width => "100%", :height => "35", :border => "0"), product.url
    - else
      = image_tag("blank2.gif", :width => "100%", :height => "35", :border => "0")
  %td{ :width => "4"}
  %td{ :width => "115", :style => "background-color:##{product.shade_2}; border: 1px solid #CCC"}
    - if product.url.present?
      = link_to image_tag("blank.gif", :width => "100%", :height => "35", :border => "0"), product.url
    - else
      = image_tag("blank2.gif", :width => "100%", :height => "35", :border => "0")
  %td.button_group
    = link_to "Bearbeiten", edit_admin_product_path(product), :class => "edit_link", :title => "Bearbeiten"
    = link_to t(:delete), admin_product_path(product), :method => :delete, :confirm => "Sind Sie sicher?", :class => "delete_link", :title => "Löschen"
    

app/views/admin/products/edit.html.haml
= link_go_back admin_products_path, :class => "right"

%h1="Produkt bearbeiten"

- form_for @product, :url => admin_product_path(@product), :method => :update do |f|
  = f.error_messages
  = render "form", :f => f
  = submit_button("Aktualisieren",f,:cancel_path => admin_products_path, :class => "right")

app/views/admin/products/index.csv.erb
id,product_group_id,number,color_name_id,info_de,info_en,shade_1,shade_2,url,created_at,updated_at
<%= FasterCSV.generate do |csv|
  Product.all(:order => "id ASC").each do |product|
    csv << [ product[:id],product[:product_group_id],product[:number],product[:color_name_id],product[:info_de],product[:info_en],product[:shade_1],product[:shade_2],product[:url],product[:created_at],product[:updated_at] ]
  end
end %>

app/views/admin/products/index.html.haml
= link_to "Produkt/Farbe erstellen", new_admin_product_path, :class => "right  post_new_link" 
%h1 Produkte / Farben
= link_to "Download CSV-Datei", admin_products_path(:format => "csv")
= link_to "Download Farbnamen", admin_color_names_path(:format => "csv")

- form_for @search do |f|
  = f.label :number_like, 'Farbnummer'
  = f.text_field :number_like, :style => "width:30px;"
  = f.submit 'Suchen'

%table.products{ :cellspacing => "0", :cellpadding => "0", :border => "0" }
  %th= order @search, :by => :number, :as => "Nummer"
  %th Ton 1
  %th 
  %th Ton 2
  = render @products
  
= will_paginate @products

app/views/admin/products/new.html.haml
= link_go_back admin_products_path, :class => "right"

%h1="Produkt erstellen"

- form_for @product, :url => admin_products_path, :html => { :method => :post } do |f|
  = f.error_messages
  = render "form", :f => f
  = submit_button("Erstellen",f,:cancel_path => admin_products_path, :class => "right")